# configs/rf_detrV4a_motip_dancetrack.yaml
SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

CKPT_PATH:      rfdetr_dancetrack_motip/checkpoint_best_total.pth
DETR_FRAMEWORK: rf_detr


SIZE_DIVISIBILITY: 32
DATA_ROOT: /data/pos+mot/Datadir/

EPOCHS: 20
LR: 1.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [12]

USE_REID_PROJ: true

USE_CONTRASTIVE: true    
CONTRASTIVE_WEIGHT:   0.05
CONTRASTIVE_TEMP:     0.3
CONTRASTIVE_PROJ_DIM: 128
CONTRASTIVE_WARMUP:   500

SAMPLE_LENGTHS: [30, ]
DETR_NUM_TRAIN_FRAMES: 0
NUM_ID_DECODER_LAYERS: 6

INFERENCE_DTYPE: FP16
NUM_WORKERS: 0

INFERENCE_TEMPERATURE: 1.0
